# Generated by Django 5.2.4 on 2025-07-09 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_classroom_quiz_question_studentquizattempt_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentquizattempt",
            name="score",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
