# Generated by Django 5.2.4 on 2025-07-16 21:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_question_time_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"role": "student"},
                related_name="classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
