# Generated by Django 5.2.4 on 2025-07-17 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_classroom_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="teacher",
        ),
    ]
