# Generated by Django 5.2.4 on 2025-08-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_enrollmentcode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
